### ISSUE TITLE
FIX on qball2

### ISSUE THREAD

**Issue by J-Drucker** [CVNRneuroimaging/infrastructure#168]
FSL's FIX requires MATLAB.

Alternatively (and this may be a better solution in terms of portability), it can use Octave (which is free!) instead of Matlab.

In order to use Octave, the file /opt/fix/settings.sh needs to be changed (there's a variable that tells FIX to use Octave instead of Matlab). Problem is, I don't have permissions to edit that file.

I'm cool with whatever solution you guys think preserves the integrity of our infrastructure.

Many thanks,
Jonathan

**Comment by rrmm** [comment]
Keith,

   can you put matlab on qball2?

Jonathan,

   I tend to prefer octave myself, but i think the decision was to keep
everyone on the same set of tools to ensure consistent results.

rob

**Comment by kmcgregor123456** [comment]
Matlab is already on qball2 in /usr/local/MATLAB/r2015b

# 

Keith M. McGregor, PhD
VA RR&D Atlanta CVNR
Emory University, Department of Neurology
352.359.8084
http://www.varrd.emory.edu

**Comment by J-Drucker** [comment]
Oh. Could be a path issue? Should I update my bash profile?

**Comment by J-Drucker** [comment]
Guys, I found the problem!

FIX uses the file settings.sh to set a bunch of environmental variables. One of those variables is the location of MATLAB. Line 21 looks like this:

```
   FSL_FIX_MATLAB_ROOT=/opt/fmrib/matlab
```

See the problem? That's not where MATLAB is! I can't fix the code, because I don't have permissions.

**Comment by kmcgregor123456** [comment]
I changed the settings.sh file. it should work now.

# 

Keith M. McGregor, PhD
VA RR&D Atlanta CVNR
Emory University, Department of Neurology
352.359.8084
http://www.varrd.emory.edu

**Comment by J-Drucker** [comment]
Still crashing. The file /opt/fix/settings.sh looks unchanged:

FSL_FIX_MATLAB_ROOT=/opt/fmrib/matlab

**Comment by J-Drucker** [comment]
My mistake, sort of; qball2 looks good. I'll try running it soon.

I was on lens. That settings file should probably be the same on all of the machines we'll be using, though, so maybe my mistake was fortuitous?
